FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections && \
    apt-get install -y \
        python3.11 \
        python3-pip \
        libegl1-mesa \
        libgl1-mesa-glx \
        libglib2.0-0 \
        ttf-mscorefonts-installer \
        fonts-noto-color-emoji \
        git && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

WORKDIR /app

COPY . .

RUN python -m pip install --upgrade pip && \
    pip install -e ".[test]"

CMD ["bash"]